### ISSUE TITLE
Jaggies

### ISSUE THREAD

**Issue by nathanpitman** [ihasco/Identity#2]
There are very noticeable jaggies in the 'patterns' area here:

https://ihasco.github.io/Identity/shapes.html

![screen shot 2018-09-21 at 10 35 12](https://user-images.githubusercontent.com/694545/45873335-19282d00-bd8a-11e8-90bb-ff039af4f856.png)

**Comment by Hicksdesign** [comment]
Yes, it seems that browsers don't like rendering lines straight after transforms, even if they are SVG. Fixed this example!

**Comment by nathanpitman** [comment]
Thanks, last set of images on that page have some serious jaggies too. :)

 
![screen shot 2018-09-21 at 11 18 18](https://user-images.githubusercontent.com/694545/45875612-1defdf80-bd90-11e8-8ca0-8419494e7a60.png)

**Comment by Hicksdesign** [comment]
I've removed this part, and expanded on the SVG pattern fill instead!
