### ISSUE TITLE
Tints need to include SASS mixin values

### ISSUE THREAD

**Issue by nathanpitman** [ihasco/Identity#3]
In the colour section where we refer to tints of the base colours we need to include the mixin to lighten:

![screen shot 2018-09-21 at 10 37 21](https://user-images.githubusercontent.com/694545/45873477-7cb25a80-bd8a-11e8-9f09-6e9d0dae6500.png)

i.e. these should read something like: `SASS lighten($color-black, 30%)`

**Comment by Hicksdesign** [comment]
Added :)
