### ISSUE TITLE
Is the logo in this example is misaligned?

### ISSUE THREAD

**Issue by nathanpitman** [ihasco/Identity#7]
There are not examples in the guide regarding using the pinwheel with the logotype beneath, is the alignment of the logotype here with the pinwheel really correct?

![image 1](https://user-images.githubusercontent.com/694545/46069712-05a70880-c174-11e8-88a7-e46d9661f250.png)

https://ihasco.github.io/Identity/layouts.html

**Comment by Hicksdesign** [comment]
Ah yes, I forgot to bring this up! My feeling is that there will be occasions when you need a logo of this orientation, but I haven't yet included it in the logo options. Aligning the two elements is slightly tricky however, and the above is what I felt balanced best visually. What are your thoughts?

**Comment by nathanpitman** [comment]
Yea it's prob a good balance, this was actually raised by one of the production team (at least they are looking at the guidelines!).
