### ISSUE TITLE
Facebook logo in logo pack has two green triangles

### ISSUE THREAD

**Issue by nathanpitman** [ihasco/Identity#8]
Spotted a minor issue in the logo pack. :)

<img width="2048" alt="ihasco-logo-facebook 2x" src="https://user-images.githubusercontent.com/694545/46679498-09f50c00-cbdf-11e8-9464-bc2aac26ce95.png">

**Comment by Hicksdesign** [comment]
Very odd! The individual files were correct, so I assume the zipped logo pack wasn't taken off the latest files. Have re-zipped and pushed :)

**Comment by nathanpitman** [comment]
Thanks Jon! :)
